name: ozzie
description: Ozzie is your testing friend. Ozzie will take an screenshot during integration tests whenever you need. Ozzie will capture performance reports for you.
version: 2.2.3
author: Jorge Coca<jcocaramos@gmail.com>
homepage: https://github.com/jorgecoca/ozzie.flutter

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  archive: ^3.1.11
  meta: ^1.7.0
  test:
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

flutter:
